version: '3.8'

services:
  backend:
    image: ccr.ccs.tencentyun.com/${TENCENT_ACCOUNT}/my-library-backend:${TAG:-latest}
    ports:
      - '8000:8000'
    environment:
      - PYTHONUNBUFFERED=1
      - SERVER_IP=${SERVER_IP}
    restart: unless-stopped
    volumes:
      - backend-data:/app/data

  frontend:
    image: ccr.ccs.tencentyun.com/${TENCENT_ACCOUNT}/my-library-frontend:${TAG:-latest}
    ports:
      - '80:80'
    depends_on:
      - backend
    environment:
      - REACT_APP_ENV=production
    restart: unless-stopped

volumes:
  backend-data:
    driver: local
