/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package top.dingfengbo.mylibrary.api.models

import top.dingfengbo.mylibrary.api.models.ApplicationResponse

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param applications 
 * @param total 
 * @param totalPages 
 * @param page 
 * @param limit 
 */
@Serializable

data class ApiApplicationsGet200Response (

    @SerialName(value = "applications")
    val applications: kotlin.collections.List<ApplicationResponse>? = null,

    @SerialName(value = "total")
    val total: kotlin.Int? = null,

    @SerialName(value = "total_pages")
    val totalPages: kotlin.Int? = null,

    @SerialName(value = "page")
    val page: kotlin.Int? = null,

    @SerialName(value = "limit")
    val limit: kotlin.Int? = null

) {


}

