/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package top.dingfengbo.mylibrary.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param userId 
 * @param uuid 
 * @param db 
 * @param exists 
 * @param type 
 */
@Serializable

data class ApiAuthDbInfoGet200Response (

    @SerialName(value = "user_id")
    val userId: kotlin.Int? = null,

    @SerialName(value = "uuid")
    val uuid: kotlin.String? = null,

    @SerialName(value = "db")
    val db: kotlin.String? = null,

    @SerialName(value = "exists")
    val exists: kotlin.Boolean? = null,

    @SerialName(value = "type")
    val type: kotlin.String? = null

) {


}

