/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package top.dingfengbo.mylibrary.api.models

import top.dingfengbo.mylibrary.api.models.AuthorSummary

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param authors 
 * @param totalPages 
 * @param totalAuthors 
 */
@Serializable

data class ApiAuthorsGet200Response (

    @SerialName(value = "authors")
    val authors: kotlin.collections.List<AuthorSummary>? = null,

    @SerialName(value = "total_pages")
    val totalPages: kotlin.Int? = null,

    @SerialName(value = "total_authors")
    val totalAuthors: kotlin.Int? = null

) {


}

