/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package top.dingfengbo.mylibrary.api.models

import top.dingfengbo.mylibrary.api.models.BrandSummary

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param brands 
 * @param totalPages 
 * @param totalBrands 
 */
@Serializable

data class ApiBrandsGet200Response (

    @SerialName(value = "brands")
    val brands: kotlin.collections.List<BrandSummary>? = null,

    @SerialName(value = "total_pages")
    val totalPages: kotlin.Int? = null,

    @SerialName(value = "total_brands")
    val totalBrands: kotlin.Int? = null

) {


}

