/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package top.dingfengbo.mylibrary.api.models

import top.dingfengbo.mylibrary.api.models.ApiBooksBookIdSimilarGet200ResponseBook
import top.dingfengbo.mylibrary.api.models.ApiBooksBookIdSimilarGet200ResponseSimilarBooksInner

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param book 
 * @param similarBooks 
 */
@Serializable

data class ApiBooksBookIdSimilarGet200Response (

    @SerialName(value = "book")
    val book: ApiBooksBookIdSimilarGet200ResponseBook? = null,

    @SerialName(value = "similar_books")
    val similarBooks: kotlin.collections.List<ApiBooksBookIdSimilarGet200ResponseSimilarBooksInner>? = null

) {


}

