/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package top.dingfengbo.mylibrary.api.models

import top.dingfengbo.mylibrary.api.models.CategorySummary

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param categories 
 * @param totalPages 
 * @param totalCategories 
 */
@Serializable

data class ApiCategoriesGet200Response (

    @SerialName(value = "categories")
    val categories: kotlin.collections.List<CategorySummary>? = null,

    @SerialName(value = "total_pages")
    val totalPages: kotlin.Int? = null,

    @SerialName(value = "total_categories")
    val totalCategories: kotlin.Int? = null

) {


}

