/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package top.dingfengbo.mylibrary.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param total 
 * @param synced 
 * @param failed 
 */
@Serializable

data class ApiExportSyncToRootPost200ResponseCountsValue (

    @SerialName(value = "total")
    val total: kotlin.Int? = null,

    @SerialName(value = "synced")
    val synced: kotlin.Int? = null,

    @SerialName(value = "failed")
    val failed: kotlin.Int? = null

) {


}

