/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package top.dingfengbo.mylibrary.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * What the sync observed about root.db while it ran. Unknown keys are ignored by clients, so this may grow without a breaking change.
 *
 * @param rootDbTables 
 * @param rootDbPath 
 * @param rootDbError 
 */
@Serializable

data class ApiExportSyncToRootPost200ResponseDiagnostics (

    @SerialName(value = "root_db_tables")
    val rootDbTables: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "root_db_path")
    val rootDbPath: kotlin.String? = null,

    @SerialName(value = "root_db_error")
    val rootDbError: kotlin.String? = null

) {


}

