/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package top.dingfengbo.mylibrary.api.models

import top.dingfengbo.mylibrary.api.models.ApiExportSyncToRootPost200ResponseCountsValue

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param message 
 * @param differential 
 * @param counts 
 */
@Serializable

data class ApiExportSyncToRootPost200Response (

    @SerialName(value = "message")
    val message: kotlin.String? = null,

    @SerialName(value = "differential")
    val differential: kotlin.Boolean? = null,

    @Contextual @SerialName(value = "counts")
    val counts: kotlin.collections.Map<kotlin.String, ApiExportSyncToRootPost200ResponseCountsValue>? = null

) {


}

