/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package top.dingfengbo.mylibrary.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param ip 
 * @param path 
 * @param timestamp Naive local ISO-8601, no timezone
 */
@Serializable

data class ApiStatsVisitsGet200ResponseInner (

    @SerialName(value = "ip")
    val ip: kotlin.String? = null,

    @SerialName(value = "path")
    val path: kotlin.String? = null,

    /* Naive local ISO-8601, no timezone */
    @SerialName(value = "timestamp")
    val timestamp: kotlin.String? = null

) {


}

