/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package top.dingfengbo.mylibrary.api.models

import top.dingfengbo.mylibrary.api.models.ApiStatsBooksGet200ResponseOverview
import top.dingfengbo.mylibrary.api.models.ApiStatsBooksGet200ResponsePurchaseMonthsInner
import top.dingfengbo.mylibrary.api.models.ApiStatsBooksGet200ResponsePurchaseYearsInner
import top.dingfengbo.mylibrary.api.models.ApiStatsBooksGet200ResponseTimelineMonthsInner
import top.dingfengbo.mylibrary.api.models.ApiStatsBooksGet200ResponseTimelineYearsInner
import top.dingfengbo.mylibrary.api.models.NameCount

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param overview 
 * @param byReadState 
 * @param byCategory 
 * @param byBinding 
 * @param byLanguage 
 * @param topAuthors 
 * @param topPublishers 
 * @param byScore Buckets: \"9.0+\", \"8.0-8.9\", \"7.0-7.9\", \"6.0-6.9\", \"< 6.0\"; empty buckets are omitted
 * @param byCompose 
 * @param timelineMonths 
 * @param timelineYears 
 * @param purchaseMonths 
 * @param purchaseYears 
 */
@Serializable

data class ApiStatsBooksGet200Response (

    @SerialName(value = "overview")
    val overview: ApiStatsBooksGet200ResponseOverview? = null,

    @SerialName(value = "by_read_state")
    val byReadState: kotlin.collections.List<NameCount>? = null,

    @SerialName(value = "by_category")
    val byCategory: kotlin.collections.List<NameCount>? = null,

    @SerialName(value = "by_binding")
    val byBinding: kotlin.collections.List<NameCount>? = null,

    @SerialName(value = "by_language")
    val byLanguage: kotlin.collections.List<NameCount>? = null,

    @SerialName(value = "top_authors")
    val topAuthors: kotlin.collections.List<NameCount>? = null,

    @SerialName(value = "top_publishers")
    val topPublishers: kotlin.collections.List<NameCount>? = null,

    /* Buckets: \"9.0+\", \"8.0-8.9\", \"7.0-7.9\", \"6.0-6.9\", \"< 6.0\"; empty buckets are omitted */
    @SerialName(value = "by_score")
    val byScore: kotlin.collections.List<NameCount>? = null,

    @SerialName(value = "by_compose")
    val byCompose: kotlin.collections.List<NameCount>? = null,

    @SerialName(value = "timeline_months")
    val timelineMonths: kotlin.collections.List<ApiStatsBooksGet200ResponseTimelineMonthsInner>? = null,

    @SerialName(value = "timeline_years")
    val timelineYears: kotlin.collections.List<ApiStatsBooksGet200ResponseTimelineYearsInner>? = null,

    @SerialName(value = "purchase_months")
    val purchaseMonths: kotlin.collections.List<ApiStatsBooksGet200ResponsePurchaseMonthsInner>? = null,

    @SerialName(value = "purchase_years")
    val purchaseYears: kotlin.collections.List<ApiStatsBooksGet200ResponsePurchaseYearsInner>? = null

) {


}

