/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package top.dingfengbo.mylibrary.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param totalBooks 
 * @param totalAuthors 
 * @param totalPublishers 
 * @param totalCategories 
 * @param avgPrice 
 * @param avgPurchasePrice 
 * @param totalSpent 
 */
@Serializable

data class ApiStatsBooksGet200ResponseOverview (

    @SerialName(value = "total_books")
    val totalBooks: kotlin.Int? = null,

    @SerialName(value = "total_authors")
    val totalAuthors: kotlin.Int? = null,

    @SerialName(value = "total_publishers")
    val totalPublishers: kotlin.Int? = null,

    @SerialName(value = "total_categories")
    val totalCategories: kotlin.Int? = null,

    @Contextual @SerialName(value = "avg_price")
    val avgPrice: java.math.BigDecimal? = null,

    @Contextual @SerialName(value = "avg_purchase_price")
    val avgPurchasePrice: java.math.BigDecimal? = null,

    @Contextual @SerialName(value = "total_spent")
    val totalSpent: java.math.BigDecimal? = null

) {


}

