/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package top.dingfengbo.mylibrary.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param label 
 * @param year 
 * @param count 
 * @param price 
 */
@Serializable

data class ApiStatsBooksGet200ResponsePurchaseYearsInner (

    @SerialName(value = "label")
    val label: kotlin.String? = null,

    @SerialName(value = "year")
    val year: kotlin.Int? = null,

    @SerialName(value = "count")
    val count: kotlin.Int? = null,

    @Contextual @SerialName(value = "price")
    val price: java.math.BigDecimal? = null

) {


}

