/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package top.dingfengbo.mylibrary.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param name 
 * @param nameCn 
 * @param nation Must be one of /api/authors/nations
 * @param dynasty 
 * @param intro 
 * @param photo 
 */
@Serializable

data class AuthorCreation (

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "name_cn")
    val nameCn: kotlin.String,

    /* Must be one of /api/authors/nations */
    @SerialName(value = "nation")
    val nation: kotlin.String? = "无",

    @SerialName(value = "dynasty")
    val dynasty: kotlin.String? = null,

    @SerialName(value = "intro")
    val intro: kotlin.String? = null,

    @SerialName(value = "photo")
    val photo: kotlin.String? = null

) {


}

