/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package top.dingfengbo.mylibrary.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param isbn 
 * @param title 
 * @param titleCn 
 * @param authorIds 
 * @param translator 
 * @param publisherId 
 * @param publishDate 
 * @param brandId 
 * @param bookSeriesId 
 * @param bindingType 
 * @param paperType 
 * @param pages 
 * @param bookCount 
 * @param language 
 * @param composeType 
 * @param price 
 * @param purchasePrice 
 * @param purchaseDate 
 * @param thumbImage 
 * @param categoryId 
 * @param bookshelfId 
 * @param readState 
 * @param catalog 
 * @param introduction 
 * @param summary 
 * @param registered 
 * @param edition 
 * @param printingInfo 
 * @param printedNumber 
 * @param doubanScore 
 * @param purchaseStore 
 * @param tags 
 * @param inWish 
 * @param createdAt 
 * @param updatedAt 
 */
@Serializable

data class BookCreation (

    @SerialName(value = "isbn")
    val isbn: kotlin.String,

    @SerialName(value = "title")
    val title: kotlin.String,

    @SerialName(value = "title_cn")
    val titleCn: kotlin.String,

    @SerialName(value = "author_ids")
    val authorIds: kotlin.collections.List<kotlin.Int>? = null,

    @SerialName(value = "translator")
    val translator: kotlin.String? = null,

    @SerialName(value = "publisher_id")
    val publisherId: kotlin.Int? = null,

    @SerialName(value = "publish_date")
    val publishDate: kotlin.String? = null,

    @SerialName(value = "brand_id")
    val brandId: kotlin.Int? = null,

    @SerialName(value = "book_series_id")
    val bookSeriesId: kotlin.Int? = null,

    @SerialName(value = "binding_type")
    val bindingType: kotlin.String? = null,

    @SerialName(value = "paper_type")
    val paperType: kotlin.String? = null,

    @SerialName(value = "pages")
    val pages: kotlin.Int? = null,

    @SerialName(value = "book_count")
    val bookCount: kotlin.Int? = null,

    @SerialName(value = "language")
    val language: kotlin.String? = null,

    @SerialName(value = "compose_type")
    val composeType: kotlin.String? = null,

    @Contextual @SerialName(value = "price")
    val price: java.math.BigDecimal? = null,

    @Contextual @SerialName(value = "purchase_price")
    val purchasePrice: java.math.BigDecimal? = null,

    @SerialName(value = "purchase_date")
    val purchaseDate: kotlin.String? = null,

    @SerialName(value = "thumb_image")
    val thumbImage: kotlin.String? = null,

    @SerialName(value = "category_id")
    val categoryId: kotlin.Int? = null,

    @SerialName(value = "bookshelf_id")
    val bookshelfId: kotlin.Int? = null,

    @SerialName(value = "read_state")
    val readState: kotlin.String? = null,

    @SerialName(value = "catalog")
    val catalog: kotlin.String? = null,

    @SerialName(value = "introduction")
    val introduction: kotlin.String? = null,

    @SerialName(value = "summary")
    val summary: kotlin.String? = null,

    @SerialName(value = "registered")
    val registered: kotlin.Boolean? = null,

    @SerialName(value = "edition")
    val edition: kotlin.String? = null,

    @SerialName(value = "printing_info")
    val printingInfo: kotlin.String? = null,

    @SerialName(value = "printed_number")
    val printedNumber: kotlin.Int? = null,

    @Contextual @SerialName(value = "douban_score")
    val doubanScore: java.math.BigDecimal? = null,

    @SerialName(value = "purchase_store")
    val purchaseStore: kotlin.String? = null,

    @SerialName(value = "tags")
    val tags: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "in_wish")
    val inWish: kotlin.Boolean? = null,

    @SerialName(value = "created_at")
    val createdAt: kotlin.String? = null,

    @SerialName(value = "updated_at")
    val updatedAt: kotlin.String? = null

) {


}

