/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package top.dingfengbo.mylibrary.api.models

import top.dingfengbo.mylibrary.api.models.IdName

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Slim book shape returned by every paginated book-list endpoint. `authors` are display strings (\"[宋] 苏轼\" / \"[中国] 鲁迅\"), not objects. 
 *
 * @param id 
 * @param isbn 
 * @param titleCn 
 * @param title 
 * @param thumbImage 
 * @param authors 
 * @param publisher 
 * @param category 
 */
@Serializable

data class BookCard (

    @SerialName(value = "id")
    val id: kotlin.Int? = null,

    @SerialName(value = "isbn")
    val isbn: kotlin.String? = null,

    @SerialName(value = "title_cn")
    val titleCn: kotlin.String? = null,

    @SerialName(value = "title")
    val title: kotlin.String? = null,

    @SerialName(value = "thumb_image")
    val thumbImage: kotlin.String? = null,

    @SerialName(value = "authors")
    val authors: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "publisher")
    val publisher: IdName? = null,

    @SerialName(value = "category")
    val category: IdName? = null

) {


}

