/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package top.dingfengbo.mylibrary.api.models

import top.dingfengbo.mylibrary.api.models.BookCard

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param books 
 * @param totalPages 
 * @param totalBooks 
 */
@Serializable

data class BookListPage (

    @SerialName(value = "books")
    val books: kotlin.collections.List<BookCard>? = null,

    @SerialName(value = "total_pages")
    val totalPages: kotlin.Int? = null,

    @SerialName(value = "total_books")
    val totalBooks: kotlin.Int? = null

) {


}

