/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package top.dingfengbo.mylibrary.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param title 
 * @param titleCn 
 * @param thumbImage 
 * @param isbn 
 * @param authors 
 */
@Serializable

data class BookSimple (

    @SerialName(value = "id")
    val id: kotlin.Int? = null,

    @SerialName(value = "title")
    val title: kotlin.String? = null,

    @SerialName(value = "title_cn")
    val titleCn: kotlin.String? = null,

    @SerialName(value = "thumb_image")
    val thumbImage: kotlin.String? = null,

    @SerialName(value = "isbn")
    val isbn: kotlin.String? = null,

    @SerialName(value = "authors")
    val authors: kotlin.collections.List<kotlin.String>? = null

) {


}

