/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package top.dingfengbo.mylibrary.api.models

import top.dingfengbo.mylibrary.api.models.BookSimple

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param name 
 * @param books 
 * @param parent 
 * @param intro 
 * @param depth 
 * @param path 
 * @param weight 
 */
@Serializable

data class CategoryResponse (

    @SerialName(value = "id")
    val id: kotlin.Int,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "books")
    val books: kotlin.collections.List<BookSimple>,

    @SerialName(value = "parent")
    val parent: kotlin.Int? = null,

    @SerialName(value = "intro")
    val intro: kotlin.String? = null,

    @SerialName(value = "depth")
    val depth: kotlin.Int? = null,

    @SerialName(value = "path")
    val path: kotlin.String? = null,

    @SerialName(value = "weight")
    val weight: kotlin.Int? = 0

) {


}

