/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package top.dingfengbo.mylibrary.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param isbn 
 * @param title 
 * @param titleCn 
 * @param publisherName 
 * @param publisherId 
 * @param publishDate 
 * @param pages 
 * @param price 
 * @param summary 
 * @param introduction 
 * @param thumbImage 
 * @param bindingType 
 * @param doubanScore 
 * @param authorNames 
 * @param authorIds 
 * @param translator 
 * @param language 
 * @param source 
 * @param link 
 * @param catalog 
 * @param tagNames 
 * @param authorIntro 
 * @param brandId 
 * @param brandName 
 * @param bookId 
 * @param bookName 
 * @param bookSeriesId 
 * @param bookSeriesName 
 * @param paperType 
 * @param bookCount 
 * @param composeType 
 * @param edition 
 * @param printingInfo 
 * @param printedNumber 
 * @param categoryId 
 * @param categoryPath 
 */
@Serializable

data class IsbnLookupResponse (

    @SerialName(value = "isbn")
    val isbn: kotlin.String,

    @SerialName(value = "title")
    val title: kotlin.String? = "",

    @SerialName(value = "title_cn")
    val titleCn: kotlin.String? = "",

    @SerialName(value = "publisher_name")
    val publisherName: kotlin.String? = "",

    @SerialName(value = "publisher_id")
    val publisherId: kotlin.Int? = null,

    @SerialName(value = "publish_date")
    val publishDate: kotlin.String? = "",

    @SerialName(value = "pages")
    val pages: kotlin.Int? = null,

    @Contextual @SerialName(value = "price")
    val price: java.math.BigDecimal? = null,

    @SerialName(value = "summary")
    val summary: kotlin.String? = "",

    @SerialName(value = "introduction")
    val introduction: kotlin.String? = "",

    @SerialName(value = "thumb_image")
    val thumbImage: kotlin.String? = "",

    @SerialName(value = "binding_type")
    val bindingType: kotlin.String? = "",

    @Contextual @SerialName(value = "douban_score")
    val doubanScore: java.math.BigDecimal? = null,

    @SerialName(value = "author_names")
    val authorNames: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "author_ids")
    val authorIds: kotlin.collections.List<kotlin.Int>? = null,

    @SerialName(value = "translator")
    val translator: kotlin.String? = "",

    @SerialName(value = "language")
    val language: kotlin.String? = "",

    @SerialName(value = "source")
    val source: kotlin.String? = "",

    @SerialName(value = "link")
    val link: kotlin.String? = "",

    @SerialName(value = "catalog")
    val catalog: kotlin.String? = "",

    @SerialName(value = "tag_names")
    val tagNames: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "author_intro")
    val authorIntro: kotlin.String? = "",

    @SerialName(value = "brand_id")
    val brandId: kotlin.Int? = null,

    @SerialName(value = "brand_name")
    val brandName: kotlin.String? = null,

    @SerialName(value = "book_id")
    val bookId: kotlin.Int? = null,

    @SerialName(value = "book_name")
    val bookName: kotlin.String? = "",

    @SerialName(value = "book_series_id")
    val bookSeriesId: kotlin.Int? = null,

    @SerialName(value = "book_series_name")
    val bookSeriesName: kotlin.String? = "",

    @SerialName(value = "paper_type")
    val paperType: kotlin.String? = "",

    @SerialName(value = "book_count")
    val bookCount: kotlin.Int? = null,

    @SerialName(value = "compose_type")
    val composeType: kotlin.String? = "",

    @SerialName(value = "edition")
    val edition: kotlin.String? = "",

    @SerialName(value = "printing_info")
    val printingInfo: kotlin.String? = "",

    @SerialName(value = "printed_number")
    val printedNumber: kotlin.Int? = null,

    @SerialName(value = "category_id")
    val categoryId: kotlin.Int? = null,

    @SerialName(value = "category_path")
    val categoryPath: kotlin.String? = null

) {


}

