/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package top.dingfengbo.mylibrary.api.models

import top.dingfengbo.mylibrary.api.models.RagSearchResultItem

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param query 
 * @param total 
 * @param results 
 */
@Serializable

data class RagSearchResponse (

    @SerialName(value = "query")
    val query: kotlin.String,

    @SerialName(value = "total")
    val total: kotlin.Int,

    @SerialName(value = "results")
    val results: kotlin.collections.List<RagSearchResultItem>

) {


}

