/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package top.dingfengbo.mylibrary.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param indexedCount 
 * @param totalBooks 
 * @param modelLoaded 
 * @param reindexStatus 
 * @param reindexIndexed 
 * @param reindexFailed 
 * @param reindexTotal 
 * @param reindexDetail 
 */
@Serializable

data class RagStatusResponse (

    @SerialName(value = "indexed_count")
    val indexedCount: kotlin.Int,

    @SerialName(value = "total_books")
    val totalBooks: kotlin.Int,

    @SerialName(value = "model_loaded")
    val modelLoaded: kotlin.Boolean,

    @SerialName(value = "reindex_status")
    val reindexStatus: kotlin.String? = "idle",

    @SerialName(value = "reindex_indexed")
    val reindexIndexed: kotlin.Int? = 0,

    @SerialName(value = "reindex_failed")
    val reindexFailed: kotlin.Int? = 0,

    @SerialName(value = "reindex_total")
    val reindexTotal: kotlin.Int? = 0,

    @SerialName(value = "reindex_detail")
    val reindexDetail: kotlin.String? = ""

) {


}

