/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package top.dingfengbo.mylibrary.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param query 
 * @param topK 
 * @param alpha Vector weight (0 = FTS5 only, 1 = pure vector)
 */
@Serializable

data class RagSearchRequest (

    @SerialName(value = "query")
    val query: kotlin.String,

    @SerialName(value = "top_k")
    val topK: kotlin.Int? = 10,

    /* Vector weight (0 = FTS5 only, 1 = pure vector) */
    @Contextual @SerialName(value = "alpha")
    val alpha: java.math.BigDecimal? = java.math.BigDecimal("0.5")

) {


}

