/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package top.dingfengbo.mylibrary.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param bookId 
 * @param score 
 * @param title 
 * @param titleCn 
 * @param authors 
 */
@Serializable

data class RagSearchResultItem (

    @SerialName(value = "book_id")
    val bookId: kotlin.Int,

    @Contextual @SerialName(value = "score")
    val score: java.math.BigDecimal,

    @SerialName(value = "title")
    val title: kotlin.String? = null,

    @SerialName(value = "title_cn")
    val titleCn: kotlin.String? = null,

    @SerialName(value = "authors")
    val authors: kotlin.collections.List<kotlin.String>? = null

) {


}

