/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package top.dingfengbo.mylibrary.api.models

import top.dingfengbo.mylibrary.api.models.ReadingPlanSummary

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param readingPlans 
 * @param totalPages 
 * @param totalPlans 
 */
@Serializable

data class ReadingPlanListResponse (

    @SerialName(value = "reading_plans")
    val readingPlans: kotlin.collections.List<ReadingPlanSummary>,

    @SerialName(value = "total_pages")
    val totalPages: kotlin.Int,

    @SerialName(value = "total_plans")
    val totalPlans: kotlin.Int

) {


}

