/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package top.dingfengbo.mylibrary.api.models

import top.dingfengbo.mylibrary.api.models.ReadingPlanBookSimple

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param name 
 * @param intro 
 * @param startDate 
 * @param endDate 
 * @param createdAt 
 * @param totalBooks 
 * @param progress 
 * @param books 
 */
@Serializable

data class ReadingPlanResponse (

    @SerialName(value = "id")
    val id: kotlin.Int,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "intro")
    val intro: kotlin.String? = null,

    @SerialName(value = "start_date")
    val startDate: kotlin.String? = null,

    @SerialName(value = "end_date")
    val endDate: kotlin.String? = null,

    @SerialName(value = "created_at")
    val createdAt: kotlin.String? = null,

    @SerialName(value = "total_books")
    val totalBooks: kotlin.Int? = null,

    @Contextual @SerialName(value = "progress")
    val progress: java.math.BigDecimal? = null,

    @SerialName(value = "books")
    val books: kotlin.collections.List<ReadingPlanBookSimple>? = null

) {


}

