/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package top.dingfengbo.mylibrary.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param accessToken 
 * @param userId 
 * @param username 
 * @param uuid 
 * @param tokenType 
 */
@Serializable

data class TokenResponse (

    @SerialName(value = "access_token")
    val accessToken: kotlin.String,

    @SerialName(value = "user_id")
    val userId: kotlin.Int,

    @SerialName(value = "username")
    val username: kotlin.String,

    @SerialName(value = "uuid")
    val uuid: kotlin.String,

    @SerialName(value = "token_type")
    val tokenType: kotlin.String? = "bearer"

) {


}

