/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package top.dingfengbo.mylibrary.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param username 
 * @param uuid 
 * @param createdAt 
 */
@Serializable

data class UserInfo (

    @SerialName(value = "id")
    val id: kotlin.Int,

    @SerialName(value = "username")
    val username: kotlin.String,

    @SerialName(value = "uuid")
    val uuid: kotlin.String,

    @SerialName(value = "created_at")
    val createdAt: kotlin.String? = null

) {


}

